name: Notify Failure

on:
  workflow_call:

permissions:
  contents: read
  pull-requests: write

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        id: notify-failure-step

        with:
          script: |
            const message_1 = `For more details, download the artifact, extract the content, and upload the file trace.zip to https://trace.playwright.dev/, this allows for online debugging.`;
            const message_2 = `However, it is also possible to check locally in the project directory using the next command: just show-trace {{path-of-trace.zip}}`;
            core.summary.addHeading("❌ Some tests failed ❌")
                          .addRaw(message_1)
                          .addRaw(message_2)
                          .write();
