name: Smoke Tests Pipeline

on:
  push:
    branches:
      - main
      - develop

permissions:
  pull-requests: write

concurrency:
  group: smoke-tests-pipeline-${{ github.ref }}
  cancel-in-progress: false

jobs:
  run-smoke-tests:
    concurrency:
      group: smoke-tests
      cancel-in-progress: false
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: "0"

      - name: Setup test
        uses: ./.github/actions/setup-test
        timeout-minutes: 60

      - name: Verify Just Installation
        shell: bash
        run: just --version

      - name: Verify UV Installation
        shell: bash
        run: uv --version

      - name: Run Smoke Tests on dev
        run: just test-ci-dev

      - name: Run Smoke Tests on prod
        run: just test-ci-prod

      - name: Notify Failure
        if: failure()
        uses: ./.github/actions/notify-failure


